# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 645f7c610b9014b5530f1aee85e02fa6f8bb4b9a6cdb64187449bf74b7314af76f7193948d22ae9dd8085148831b26c74d64cd06b842dfcecd188ceea6170f42

test:
  secret_key_base: 8850199f628841b916063958947c7fa6077ca070ad9dcb52f9c5e854cd7857a6b52bae0f85ea28452d717b6908b7c8d5a40a9573121e5b5d690d887ad41afd88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
